import 'package:get/get_navigation/get_navigation.dart';
class MyLocale implements Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    "ar": {
      'Wrong password':'كلمه مرور خاطئ',
      'Reset':'اعاده تعيين',
      'Email address must not be empty':'لا يجب ان يكون عنوان البريد فارغا',
      'Please Enter The Correct Email':'الرجاء ادخال البريد الاكترونى الصحيح',
      'User not found':'لم يتم العثور على المستخدم',
      'Log in':'تسجيل الدخول',
      'Log out':'تسجيل الخروج',
      'Reset password':'اعاده تعيين كلمه المرور',
      'Add Task':'اضافه مهمه',
      'Enter your email':'ادخل بريدك الاكترونى',
      'Password':'كلمه المرور',
      'Record':'تسجيل',
      'Upload':'رفع المحاضرات',
      'Uploaded files':'الملفات المرفوعه',
      'Attendance':'الحضور',
      'Attendance List':'بيانات الحضور',
      'Control':'التحكم',
      'Notify':'تنبيه',
      'Quiz':'اختبار',
      'Forgot your password?':'نسيت كلمه المرور ؟',
      'Forgot password ?':'نسيت كلمه المرور ؟',
      'Home':' الصفحه الرئيسيه',
      'Statistics':'احصائيات',
      'ToDo':'المهام',
      'Settings':'الاعدادات',
      'Browse Files':'اختيار ملف',
      'Send':'ارسال',
      'Upload File':' رفع ملف  ',
      'Start': 'ابدأ',
      'Tasks':'المهام',
      'New task':'مهمه جديده',
      'Add':'اضافه',
      'Notify Students':'تنبيه الطلاب',
      "language":"اللغة",
      "About App":"حول",
      "Notification":"اشعار",
      'Account':'حسابي',
      'Change Photo':'تغيير الصورة',
      'Check Now':'التأكد الان',
      "Change password":"تغيير كلمه المرور",
      'Professor':'دكتور',
      'Email':'بريد الكترونى',
      'Edit':'تعديل',
      'Name':'الاسم',
      'Date Of Event :':'تاريخ الحدث :',
      'Projector':'شاشه العرض',
      "Save":"حفظ",
      'Do you have a sudden emergancy?':'هل لديك حاله طوارئ مفاجئه ؟',
      'Dont worry ,Now you can notify your students':'لا تقلق يمكنك اخطار طلابك',
      "What news you want to share?":"ما الاخبار التى تريد ان ترسلها ؟",
      'Confirm password':'تأكيد كلمه المرور',
      'New password':'كلمه مرور جديدة',
      'Current password':'كلمه مرور الحالية',
      'Password must not be empty':'يجب ألا تكون كلمه المرور فارغه',
      'Role':'المسمى الوظيفى',
      'Years Plan':'الخطه الزمنيه',
      'My Lecture Schedule':'جدول المحاضرات',
      'Calender':'التقويم',
      'Contact with technical man':' تواصل مع الفنى المختص'
    },
    "en": {
          'Uploaded files':'Uploaded files',
          'Attendance List':'Attendance List',
          'Calender':'Calender',
          'Role':'Role',
          'Check Now':'Check Now',
          'Contact with technical man':'Contact with technical man',
          'My Lecture Schedule': 'My Lecture Schedule',
          'Years Plan':'Years Plan',
          'Projector':'Projector',
          'Confirm password':'Confirm password',
          'New password':'New password',
          'Current password':'Current password',
          'Password must not be empty':'Password must not be empty',
          'Change Photo':'Change Photo',
          "Change password":"Change password",
          'Reset password':'Reset password',
          'Professor':'Professor',
          'Date Of Event :':'Date Of Event :',
          'Email':'Email',
          'Edit':'Edit',
          'Name':'Name',
          "Save":"Save",
          'Do you have a sudden emergancy?':'Do you have a sudden emergancy?',
          'Dont worry ,Now you can notify your students':'Dont worry ,Now you can notify your students',
          "What news you want to share?":"What news you want to share?",
          "language":"language",
          "About App":"About App",
          "Notification":"Notification",
          'Account':'Account',
          'Notify Students':'Notify Students',
          'Wrong password':'Wrong password',
          'Reset':'Reset',
          'Email address must not be empty':'Email address must not be empty',
          'Please Enter The Correct Email':'Please Enter The Correct Email',
          'user not found':'user not found',
          'Add':'Add',
          'Log in':'log in',
          'New task':'New task',
          'Add Task':'Add Task',
          'Enter your Email':'Enter your email',
          'Password':'Password',
          'Forget your password?':'Forget your password?',
          'Forgot password ?':'Forgot password ?',
          'Record':'Record',
          'Upload':'UpLoad',
          'Attendance':'Attendance',
          'Control':'Control',
          'Notify':'Notify',
          'Quiz':'Quiz',
          'Home':'Home',
          'Statistics':'Statistics',
          'ToDo':'ToDo',
          'Settings':'Settings',
          'Browse Files':'Browse Files',
          'Send':'Send',
          'Upload File':'Upload File',
          'Start': 'Start',
          ' Tasks':'Tasks',

    },
  };
}