 // File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUT6M82ZUCpt33RNo4n_8ONXyabMHiuEs',
    appId: '1:154111777957:web:a052d22201477a4f1f014c',
    messagingSenderId: '154111777957',
    projectId: 'uploadfiles-891be',
    authDomain: 'uploadfiles-891be.firebaseapp.com',
    storageBucket: 'uploadfiles-891be.appspot.com',
    measurementId: 'G-3VFG89CGE4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCilpQzVtYcW8l8sSQi5rC54i890vpJacI',
    appId: '1:154111777957:android:c6fdafe83000cf091f014c',
    messagingSenderId: '154111777957',
    projectId: 'uploadfiles-891be',
    storageBucket: 'uploadfiles-891be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7LS4hplu8Vmqbyq9QjyLSI9b301Vkj_Y',
    appId: '1:154111777957:ios:d558596155f217941f014c',
    messagingSenderId: '154111777957',
    projectId: 'uploadfiles-891be',
    storageBucket: 'uploadfiles-891be.appspot.com',
    androidClientId: '154111777957-4l106ocb9avl7610gmjs0n46rqhe8soj.apps.googleusercontent.com',
    iosClientId: '154111777957-k9ccsjqc81tam3koapb4odihinsk39hb.apps.googleusercontent.com',
    iosBundleId: 'com.example.lectureApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7LS4hplu8Vmqbyq9QjyLSI9b301Vkj_Y',
    appId: '1:154111777957:ios:d558596155f217941f014c',
    messagingSenderId: '154111777957',
    projectId: 'uploadfiles-891be',
    storageBucket: 'uploadfiles-891be.appspot.com',
    androidClientId: '154111777957-4l106ocb9avl7610gmjs0n46rqhe8soj.apps.googleusercontent.com',
    iosClientId: '154111777957-k9ccsjqc81tam3koapb4odihinsk39hb.apps.googleusercontent.com',
    iosBundleId: 'com.example.lectureApp',
  );
}
