name: lecture_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  get: ^4.6.5
  webview_flutter: ^4.0.4
  flutter_inappwebview: ^5.7.2+3
 # modal_progress_hud_nsn: ^0.3.0
  flutter_native_splash: ^2.2.14
  animated_splash_screen: ^1.3.0
  lottie: ^2.3.1
  file_picker: ^5.2.5
  firebase_core: ^2.4.1
  firebase_storage: ^11.0.10
  firebase_auth: ^4.2.5
  firebase_analytics: ^10.1.0
  cloud_firestore: ^4.3.1
  firebase_database: ^10.0.9
  flutter_secure_storage: ^7.0.1
  googleapis_auth: ^1.3.1
  googleapis: ^10.0.0
  path_provider: ^2.0.12
  dotted_border: ^2.0.0+3
  google_fonts: ^3.0.1
  google_sign_in: ^5.4.3
  fluttertoast: ^8.1.2
  curved_navigation_bar: ^1.0.3
  provider: ^6.0.5
  stop_watch_timer: ^2.0.0
  flutter_colorpicker: ^1.0.3
  ionicons: ^0.2.2
  image_picker: ^0.8.6+2
  shared_preferences: ^2.0.17
  table_calendar: ^3.0.8
  http: ^0.13.5
  url_launcher: ^6.1.10
  font_awesome_flutter: ^10.4.0
  toggle_switch: ^2.1.0

  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - R/icons/
    - R/images/
    - R/

  fonts:
    - family: Poppins
      fonts:
          - asset: R/fonts/Poppins-Regular.ttf
    - family: Microsoft PhagsPa
      fonts:
        - asset: R/fonts/phagspa.ttf

    - family: Segoe Print
      fonts:
        - asset: R/fonts/segoepr.ttf

